logging:
  level:
    ROOT: DEBUG
    com.kian: DEBUG
    io.github.jhipster: DEBUG

spring:
  application:
    name: accounting
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL=TCP)(HOST=172.16.10.122)(PORT=1521)))(CONNECT_DATA=(SID=ora12c)(GLOBAL_NAME=ora12c)(SERVER=DEDICATED)))
    username: KD_ACCOUNTING_DEV
    password: bwIYWTok

  jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      database: ORACLE
      show-sql: true
      properties:
        hibernate.hbm2ddl.auto: none
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        hibernate.cache.hazelcast.instance_name: kdaccounting
        hibernate.cache.use_minimal_puts: true
        hibernate.cache.hazelcast.use_lite_member: true
#  mail:
#    host: localhost
#    port: 25
#    username: null
#    password: null
  messages:
    cache-seconds: 1
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true
liquibase:
  enabled: true

server:
  port: 8081
jhipster:
  http:
    version: V_1_1
  cache:
    hazelcast:
      time-to-live-seconds: 3600
      backup-count: 1
      management-center:
        enabled: false
        update-interval: 3
        url: http://localhost:8180/mancenter
#  security:
#
#    authentication:
#      jwt:
#        secret: my-secret-token-to-change-in-production
#        token-validity-in-seconds: 86400
#        token-validity-in-seconds-for-remember-me: 2592000

  metrics:
    jmx.enabled: true
    graphite:
      enabled: false
      host: localhost
      port: 2003
      prefix: kmaccounting
    prometheus:
      enabled: false
      endpoint: /prometheusMetrics
    logs:
      enabled: false
      report-frequency: 60

security:
  basic:
    enabled: false
  sessions: stateless
  user:
    password: none
  oauth2:
      client:
        accessTokenUri: http://sit.kiandigital.com/uaa/oauth/token
        userAuthorizationUri: http://sit.kiandigital.com/uaa/oauth/authorize

      resource:
        jwt:
          key-uri: http://sit.kiandigital.com/uaa/oauth/token_key

feign:
  hystrix:
    enabled: true


service:
  activator: KianDigital
